# This workflow will build the container image for linux amd64, arm64, armv6 and push it to registry
name: Build-Push-Image

on:
  push:
    branches:
      - develop
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  archs: linux/amd64,linux/arm/v6,linux/arm64

run-name: Build and Push -- ${{ github.ref_name }}

jobs:
# Job for building and pushing a release image
  build-release:
    if: ${{github.ref_type == 'tag'}}
    runs-on: ubuntu-latest
    steps:
    # Get the code
    - name: Checkout
      uses: actions/checkout@v4

    # Get version and store in environment variable
    - name: Get version
      id: get-version
      run: |
        version=$(./gradlew -q printVersion)
        echo "projectVersion=$version" >> "$GITHUB_OUTPUT"

    # Set up QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    # Setup Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to GitHub Container Registry
    - name: Log in to ghcr.io
      uses: docker/login-action@v3
      with:
        username: benjamindls
        password: ${{ secrets.GHCR_PAT }}
        registry: ghcr.io

    # Build and push image for multiple architectures
    - name: Build and push
      uses: docker/build-push-action@v5
      env:
        PROJECT_VERSION: ${{ steps.get-version.outputs.projectVersion }}
      with:
        context: .
        push: true
        tags: ghcr.io/benjamindls/${{ github.event.repository.name }}:${{ env.PROJECT_VERSION }} , ghcr.io/benjamindls/${{ github.event.repository.name }}:latest
        platforms: ${{ env.archs }}

# Job for building and pushing a snapshot image
  build-develop:
    if: ${{github.ref_name == 'develop'}}
    runs-on: ubuntu-latest
    steps:
    # Log in to GitHub Container Registry
    - name: Log in to ghcr.io
      uses: docker/login-action@v3
      with:
        username: benjamindls
        password: ${{ secrets.GHCR_PAT }}
        registry: ghcr.io

    # Set up QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    # Setup Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build and push image in multiple architectures
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/benjamindls/${{ github.event.repository.name }}:develop
        platforms: ${{ env.archs }}

    # Delete old develop images now untagged after new one is pushed
    - name: Delete old SNAPSHOT images
      uses: actions/delete-package-versions@v4
      with:
        package-name: '${{ github.event.repository.name }}'
        package-type: 'container'
        delete-only-untagged-versions: 'true'
        token: ${{ secrets.GHCR_PAT }}
